### ISSUE TITLE
json.decoder error 

### ISSUE THREAD

**Issue by casimkhan** [D4Vinci/Cr3dOv3r#45] opened 2018-07-04 22:27 UTC
Hi just recently i have started experiencing below issue

[+] Checking email in public leaks...
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 140, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    if ispwned.check_hackedEmails(email):
  File "/home/csirt/tools/Cr3dOv3r/Core/ispwned.py", line 10, in check_hackedEmails
    res = req.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zatarra** [comment] 2018-07-10 11:34
That issue is fixed with this PR: 
https://github.com/D4Vinci/Cr3dOv3r/pull/47

**Comment by D4Vinci** [comment] 2018-07-19 09:29
Duplicate of #46 
See my answer there

**Closed by D4Vinci** 2018-07-19 09:29 UTC
Labels: Known, duplicate

**Comment by D4Vinci** [comment] 2018-07-20 23:46
Version 0.4 just released!
Fixed, added and improved many things.
Check it out!
