### ISSUE TITLE
Doesn't actually work

### ISSUE THREAD

**Issue by wurhzwj0dt** [D4Vinci/Cr3dOv3r#6] opened 2017-11-14 13:35 UTC
Even with a bogus email, and the error of "Email not found" it's still able to "login" to sites. A found address and a bogus password also does the same. 
![a](https://user-images.githubusercontent.com/28910571/32782527-b5a3bcb2-c916-11e7-8092-e1b9a37a54ab.png)

**Comment by D4Vinci** [comment] 2017-11-14 16:45
The problem is with this websites form data but I will fix it ASAP
Till fix I will close this issue as known

**Closed by D4Vinci** 2017-11-14 16:45 UTC

**Comment by D4Vinci** [comment] 2017-11-14 21:35
Released a hotfix check it out and reopen please if the problem stays!
